![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Transformez vos données en tableaux

Pour cette seconde tâche, nous travaillons toujours sur les mêmes 10 clients, mais nous avons cette fois trois informations à disposition sur chacun d’eux :
- le revenu mensuel
- l'âge du client
- le nombre d’enfants à charge

L’objectif va être de créer un tableau NumPy à partir de ces informations et de répondre aux différentes demandes formulées par notre service prêt en manipulant ce tableau avec les différentes techniques présentées tout au long de ce chapitre.

In [ ]:
import numpy as np

L'ensemble des ces informations sont rassemblées dans la liste `tableau` suivante :

In [ ]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]

display(tableau)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

A partir de cette liste, créez un array que vous nommerez `data` :

In [17]:
import numpy as np

# Chaque personne = une ligne avec [revenu, âge, sexe]
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

# ✅ Regrouper toutes les lignes dans une seule liste nommée 'tableau'
tableau = [
    hugo,
    richard,
    emilie,
    pierre,
    paul,
    deborah,
    yohann,
    anne,
    thibault,
    emmanuel
]

# Convertir en array numpy
data = np.array(tableau)

# Affichage
from IPython.display import display
display(data)


array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2]])

data = texte en italique

Paul souhaiterait contracter un prêt immobilier :
- affichez les informations qui lui sont relatives. Pour rappel, Paul correspond à la 5ème ligne de nos données
- calculez ses mensualités maximales, en sachant que le taux d'endettement maximum est de 35% (il ne pourra donc pas rembourser par mois plus de 35% de son revenu).

In [29]:
# Display information for Paul (5th line, index 4)
print("Informations for Paul:")
print(data[4])

# Calculate maximum monthly payment (35% of income)
paul_income = data[4, 0] # Get income for Paul (row 4, column 0)
max_monthly_payment = paul_income * 0.35
print(f"\nPaul's maximum monthly payment: {max_monthly_payment:.2f}")

Informations for Paul:
[2172   37    2]

Paul's maximum monthly payment: 760.20


Un nouveau client vient d'arriver, dont les informations sont les suivantes :

In [ ]:
louise = [1900, 31, 1]

Ajoutez ces informations à la suite de votre array `data` :

In [30]:
import numpy as np

# Exemple tableau avec plusieurs Louise en trop (15 lignes)
data = np.array([
    [1800, 21, 0],
    [1500, 54, 2],
    [2200, 28, 3],
    [3000, 37, 1],
    [2172, 37, 2],
    [5000, 32, 0],
    [1400, 23, 0],
    [1200, 25, 1],
    [1100, 19, 0],
    [1300, 31, 2],
    [1900, 31, 1],  # Louise
    [1900, 31, 1],  # Louise en double
    [1900, 31, 1],  # Louise en double
    [1900, 31, 1],  # Louise en double
    [1900, 31, 1]   # Louise en double
])

louise = np.array([1900, 31, 1])

# Trouver les indices des lignes identiques à Louise
mask_louise = np.all(data == louise, axis=1)

# Indices des lignes qui ne sont pas Louise
indices_non_louise = np.where(~mask_louise)[0]

# Garder la première occurrence de Louise + toutes les autres lignes non Louise
first_louise_index = np.where(mask_louise)[0][0]  # premier index de Louise

indices_a_garder = np.concatenate(([first_louise_index], indices_non_louise))
indices_a_garder = np.sort(indices_a_garder)

# Nouveau tableau sans doublons de Louise
data_sans_doublons = data[indices_a_garder]

print("Shape avant :", data.shape)
print("Shape après :", data_sans_doublons.shape)
print(data_sans_doublons)


Shape avant : (15, 3)
Shape après : (11, 3)
[[1800   21    0]
 [1500   54    2]
 [2200   28    3]
 [3000   37    1]
 [2172   37    2]
 [5000   32    0]
 [1400   23    0]
 [1200   25    1]
 [1100   19    0]
 [1300   31    2]
 [1900   31    1]]


Stockez enfin l'ensemble des informations de salaire de notre clientèle dans une variable `revenus` :

In [44]:
data = np.array([
    [1800, 21, 0],
    [1500, 54, 2],
    [2200, 28, 3],
    [3000, 37, 1],
    [2172, 37, 2],
    [5000, 32, 0],
    [1400, 23, 0],
    [1200, 25, 1],
    [1100, 19, 0],
    [1300, 31, 2],
    [1900, 31, 1]]),
revenus = data
print(revenus)

(array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2],
       [1900,   31,    1]]),)


Bien joué !

Comme d'habitude, je vous propose de retrouver la correction ci-contre proposant une solution complète, que ce soit pour vérifier votre travail ou comprendre un point qui aurait été bloquant :
[lien vers la solution](https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C4%20-%20Transformez%20vos%20donn%C3%A9es%20en%20tableaux%20-%20correction.ipynb).